AVDOMAIN="__DOMAIN__"
AVUSER="admin@__DOMAIN__"
CREATEADMIN="admin@__DOMAIN__"
CREATEADMINPASS="__ADMIN_PASS__"
CREATEDOMAIN="__DOMAIN__"
DOCREATEADMIN="yes"
DOCREATEDOMAIN="yes"
DOTRAINSA="yes"
ENABLEDEFAULTBACKUP="no"
EXPANDMENU="no"
HOSTNAME="__HOSTNAME__"
HTTPPORT="8080"
HTTPPROXYPORT="80"
HTTPPROXY="TRUE"
HTTPSPORT="8443"
HTTPSPROXYPORT="443"
IMAPPORT="7143"
IMAPPROXYPORT="143"
IMAPSSLPORT="7993"
IMAPSSLPROXYPORT="993"
INSTALL_PACKAGES="zimbra-core zimbra-ldap zimbra-logger zimbra-mta zimbra-dnscache zimbra-snmp zimbra-store zimbra-proxy"
INSTALL_WEBAPPS="service zimlet zimbra zimbraAdmin"
LDAPADMINPASS="__ADMIN_PASS__"
LDAPAMAVISPASS="__ADMIN_PASS__"
ldap_bes_searcher_password="__ADMIN_PASS__"
LDAPBESSEARCHSET="set"
ldap_dit_base_dn_config="cn=zimbra"
LDAPHOST="__HOSTNAME__"
ldap_nginx_password="__ADMIN_PASS__"
LDAPPORT="389"
LDAPPOSTPASS="__ADMIN_PASS__"
LDAPREPLICATIONTYPE="master"
LDAPREPPASS="__ADMIN_PASS__"
LDAPROOTPASS="__ADMIN_PASS__"
mailboxd_directory="/opt/zimbra/mailboxd"
mailboxd_keystore="/opt/zimbra/mailboxd/etc/keystore"
mailboxd_keystore_password="__ADMIN_PASS__"
mailboxd_server="jetty"
mailboxd_truststore_password="changeit"
MAILBOXDMEMORY="1024"
MAILPROXY="TRUE"
MODE="https"
MYSQLMEMORYPERCENT="30"
POPPORT="7110"
POPPROXYPORT="110"
POPSSLPORT="7995"
POPSSLPROXYPORT="995"
postfix_mail_owner="postfix"
postfix_setgid_group="postdrop"
PROXYMODE="https"
REMOVE="no"
RUNARCHIVING="no"
RUNAV="yes"
RUNCBPOLICYD="no"
RUNDKIM="yes"
RUNSA="yes"
RUNVMHA="no"
SERVICEWEBAPP="yes"
SMTPDEST="admin@__DOMAIN__"
SMTPHOST="__HOSTNAME__"
SMTPNOTIFY="yes"
SMTPSOURCE="admin@__DOMAIN__"
SNMPNOTIFY="yes"
SNMPTRAPHOST="__HOSTNAME__"
ssl_default_digest="sha256"
STARTSERVERS="yes"
SYSTEMMEMORY="3.8"
TRAINSAHAM="ham@__DOMAIN__"
TRAINSASPAM="spam@__DOMAIN__"
UIWEBAPPS="yes"
UPGRADE="no"
VERSIONUPDATECHECKS="FALSE"
VIRUSQUARANTINE="virus-quarantine@__DOMAIN__"
zimbraDNSMasterIP="__DNS_RESOLVER__"
zimbraDNSTCPUpstream="no"
zimbraDNSUseTCP="yes"
zimbraDNSUseUDP="yes"
zimbraIPMode="ipv4"
zimbra_ldap_userdn="uid=zimbra,cn=admins,cn=zimbra"
zimbraMailProxy="TRUE"
zimbraPrefTimeZoneId="UTC"
ZIMBRA_REQ_SECURITY="yes"
zimbra_require_interprocess_security="1"
zimbraReverseProxyLookupTarget="TRUE"
zimbraWebProxy="TRUE"
