@ENTRIES = (
   { name => "ant-1.7.0-ziputil-patched",            },
   { name => "ant-tar-patched",                      },
   { name => "ical4j-0.9.16-patched",                },
   { name => "junixsocket",                         tag    => "junixsocket-parent-2.0.4", remote => "gh-ks",},
   { name => "nekohtml-1.9.13",                      },
   { name => "java-html-sanitizer-release-20190610.1",},
   { name => "antisamy",                             },
   { name => "zm-admin-console",                     },
   { name => "zm-admin-help-common",                 },
   { name => "zm-ajax",                              },
   { name => "zm-admin-ajax",                        },
   { name => "zm-amavis",                            },
   { name => "zm-certificate-manager-store",         },
   { name => "zm-charset",                           },
   { name => "zm-core-utils",                        },
   { name => "zm-db-conf",                           },
   { name => "zm-dnscache",                         remote => "gh-zm-upstream", },
   { name => "zm-freshclam",                        remote => "gh-zm-upstream", },
   { name => "zm-jetty-conf",                        },
   { name => "zm-jython",                            },
   { name => "zm-launcher",                          },
   { name => "zm-ldap-utilities",                    },
   { name => "zm-ldap-utils-store",                  },
   { name => "zm-licenses",                          },
   { name => "zm-mailbox",                           },
   { name => "zm-migration-tools",                  remote => "gh-zm-upstream", },
   { name => "zm-mta",                               },
   { name => "zm-nginx-conf",                       remote => "gh-zm-upstream", },
   { name => "zm-openid-consumer-store",            remote => "gh-zm-upstream", },
   { name => "zm-pkg-tool",                         remote => "gh-zm-upstream", },
   { name => "zm-postfix",                           },
   { name => "zm-ssdb-ephemeral-store",             remote => "gh-zm-upstream", },
   { name => "zm-taglib",                            },
      # zm-timezones repo can be removed and made independent of zm-zextras
      # zm-timezones cannot be done unless the packages from it are pushed to public repo
      # zm-timezones is already excluded in CircleCI builds via --exclude-git-repo=...
   { name => "zm-timezones",                        remote => "gh-zm-upstream", },
   { name => "zm-web-client",                        },
   { name => "zm-zcs",                               },
   { name => "zm-zcs-lib",                           },
   { name => "zm-zimlets",                           },
);
